Controllers/ActiveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TeachPlan.Controllers
{
	public class ActiveController : Controller
	{
		public ActionResult Index ()
		{
			return View ();
		}

		public PartialViewResult Active (Active modle)
		{
			return PartialView ("_Active", modle);
		}

		[HttpGet]
		public PartialViewResult AddActive (int planId)
		{
			var active = new Active ();
			active.Plan_Id = planId;
			return PartialView ("_AddActive", active);
		}

		[HttpPost]
		public JsonResult AddActive (Active model)
		{
			var service = new ActiveService ();
			model.UserInfo_Id = int.Parse (Session ["user"].ToString ());
			model.Steps = new List<ActiveStep> ();
			service.Create (model);
			return Json (true);
		}

		[HttpPost]
		public JsonResult AddComment (Comment comment)
		{
			var service = new CommentService ();
			service.Create (comment);
			return Json (true);
		}

		[HttpGet]
		public PartialViewResult AddComment (int activeId)
		{
			var comment = new Comment ();
			comment.To_Type = (int)ToType.Active;
			comment.To_Id = activeId;
			return PartialView ("_AddComment", comment);
		}

		public PartialViewResult Subjects ()
		{
			var service = new SubjectService ();
			return PartialView ("_Subjects", service.GetAll ());
		}

		public PartialViewResult Phases ()
		{
			var service = new PhaseService ();
			return PartialView ("_Phases", service.GetAll ());
		}

		public PartialViewResult Forms ()
		{
			var service = new FormService ();
			return PartialView ("_Forms", service.GetAll ());
		}

		public PartialViewResult Contents ()
		{
			var service = new ContentService ();
			return PartialView ("_Contents", service.GetAll ());
		}

		[HttpPost]
		public PartialViewResult SearchActives ()
		{
			var forms = Request.Form;
			var phase = forms.Get ("phase");
			var form = forms.Get ("form");
			var content = forms.Get ("content");
			var subject = forms.Get ("subject");

			return SearchActivesBy ((int)Session ["user"],
			                        (form != null) ? int.Parse (form) : 0,
			                        (phase != null) ? int.Parse (phase) : 0,
			                        (content != null) ? int.Parse (content) : 0,
			                        (subject != null) ? int.Parse (subject) : 0);
		}

		/**
		public PartialViewResult SearchActives()
		{
			return SearchActives ((int)Session ["user"], 0, 0, 0, 0);
		}
**/
		public PartialViewResult SearchActivesBy (int userId, int formId, int subjectId, int phaseId, int contentId)
		{
			var service = new ActiveService ();
			var enumer = service.GetByUserId (userId, formId, subjectId, phaseId, contentId);
			var list = new List<TPlan.ActiveDetailModel> ();
			var e = enumer.GetEnumerator ();
			while (e.MoveNext ()) {
				list.Add (new TPlan.ActiveDetailModel (e.Current));
			}
			return PartialView ("_Actives", list);
		}

		public ViewResult EditActive (int activeId)
		{
			var service = new ActiveService ();
			var active = service.GetById (activeId);
			return View ("_EditActive", active);
		}

		public PartialViewResult ShowPreSetSteps (int acitveId)
		{
			ViewData ["activeId"] = acitveId;
			var service = new PreSetStepService ();
			return PartialView ("_PreSetSteps", service.GetAll ());
		}

		public PartialViewResult ShowActiveSteps(Active active)
		{
			return PartialView ("_ActiveSteps", active);
		}

		public PartialViewResult ReOrderActiveStep(int orderId,string type,int activeId)
		{
			var service = new ActiveService ();
			var tempId = 0;
			if (type == "DOWN") {
				tempId = orderId + 1;
			} else if (type == "UP") {
				tempId = orderId - 1;
			}
			var active = service.GetById (activeId);
			foreach (var s in active.Steps) {
				if (s.OrderId == tempId)
					s.OrderId = orderId;
				else if (s.OrderId == orderId)
					s.OrderId = tempId;
			}
			active.Steps.Sort ();
			service.UpdateSteps (activeId, active.Steps);
			return PartialView ("_ActiveSteps",active);
		}

		public PartialViewResult AddPreSetStepToActive (int activeId)
		{
			var ids = new List<int> ();
			foreach (var key in Request.Form.AllKeys) {
				if (key.IndexOf ("pss") != 0)
					continue;
				var selected = (Request.Form [key] == "true,false");
				if (selected) {
					ids.Add (int.Parse (key.Replace ("pss", "")));
				}
			}
			var psss = new PreSetStepService ();
			var pss = psss.GetByIds (ids);
			var service = new ActiveService ();
			var active = service.GetById (activeId);
			foreach (var s in pss) {
				var nas = new ActiveStep () {
					OrderId = (active.Steps.Count+1),
					Content = s.Content,
					Description = s.Description,
					UserDescription = s.Description
				};
				active.Steps.Add (nas);
			}

			service.UpdateSteps (activeId, active.Steps);
			return PartialView ("_ActiveSteps",active);
		}

		public static IEnumerable<SelectListItem> getAllTargetType ()
		{
			var grades = new List<SelectListItem> ();
			//var service = new ContentService();
			var g = SystemConst.TargetTypeName.GetEnumerator ();
			while (g.MoveNext ()) {
				var sli = new SelectListItem ();
				sli.Text = g.Current.Value;
				sli.Value = ((int)g.Current.Key).ToString ();
				grades.Add (sli);
			}
			return grades;
		}

		public static IEnumerable<SelectListItem> getAllPoint ()
		{
			var grades = new List<SelectListItem> ();
			//var service = new ContentService();
			var g = SystemConst.PointTypeName.GetEnumerator ();
			while (g.MoveNext ()) {
				var sli = new SelectListItem ();
				sli.Text = g.Current.Value;
				sli.Value = ((int)g.Current.Key).ToString ();
				grades.Add (sli);
			}
			return grades;
		}
	}
}

Controllers/PlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.IO;
using System.Text;
using MongoDB.Bson;
using MongoDB.Driver;
using MongoDB.Driver.Builders;
using Models;
using TPlan;

namespace TeachPlan.Controllers
{
	public class PlanController : Controller
	{
		public ActionResult Index ()
		{
			return View ();

            
		}

		/// <summary>
		/// 所有学科
		/// </summary>
		/// <returns></returns>
		public static IEnumerable<SelectListItem> getAllSubjects ()
		{
			var grades = new List<SelectListItem> ();
			var service = new SubjectService ();
			var g = service.GetAll ().GetEnumerator ();
			while (g.MoveNext ()) {
				var sli = new SelectListItem ();
				sli.Text = g.Current.Name;
				sli.Value = g.Current.MyId.ToString ();
				//if (select != null && select.Id == g.Current.Id)
				//    sli.Selected = true;
				grades.Add (sli);
			}
			return grades;
		}

		/// <summary>
		/// 所有教材
		/// </summary>
		/// <returns></returns>
		public static IEnumerable<SelectListItem> getAllTextbooks ()
		{
			var grades = new List<SelectListItem> ();
			var service = new TextbookService ();
			var g = service.GetAll ().GetEnumerator ();
			while (g.MoveNext ()) {
				var sli = new SelectListItem ();
				sli.Text = g.Current.Name;
				sli.Value = g.Current.MyId.ToString ();
				//if (select != null && select.Id == g.Current.Id)
				//    sli.Selected = true;
				grades.Add (sli);
			}
			return grades;
		}

		/// <summary>
		/// 所有目标层次
		/// </summary>
		/// <returns></returns>
		public static IEnumerable<SelectListItem> getAllPhases ()
		{
			var grades = new List<SelectListItem> ();
			var service = new PhaseService ();
			var g = service.GetAll ().GetEnumerator ();
			while (g.MoveNext ()) {
				var sli = new SelectListItem ();
				sli.Text = g.Current.Name;
				sli.Value = g.Current.MyId.ToString ();
				//if (select != null && select.Id == g.Current.Id)
				//    sli.Selected = true;
				grades.Add (sli);
			}
			return grades;
		}

		/// <summary>
		/// 所有年级
		/// </summary>
		/// <returns></returns>
		public static IEnumerable<SelectListItem> getAllGrades ()
		{
			var grades = new List<SelectListItem> ();
			var service = new GradeService ();
			var g = service.GetAll ().GetEnumerator ();
			while (g.MoveNext ()) {
				var sli = new SelectListItem ();
				sli.Text = g.Current.Name;
				sli.Value = g.Current.MyId.ToString ();
				//if (select != null && select.Id == g.Current.Id)
				//    sli.Selected = true;
				grades.Add (sli);
			}
			return grades;
		}

		/// <summary>
		/// 所有教学内容
		/// </summary>
		/// <returns></returns>
		public static IEnumerable<SelectListItem> getAllContents ()
		{
			var grades = new List<SelectListItem> ();
			var service = new ContentService ();
			var g = service.GetAll ().GetEnumerator ();
			while (g.MoveNext ()) {
				var sli = new SelectListItem ();
				sli.Text = g.Current.Name;
				sli.Value = g.Current.MyId.ToString ();
				//if (select != null && select.Id == g.Current.Id)
				//    sli.Selected = true;
				grades.Add (sli);
			}
			return grades;
		}

		/// <summary>
		/// 所有组织形式
		/// </summary>
		/// <returns></returns>
		public static IEnumerable<SelectListItem> getAllForms ()
		{
			var grades = new List<SelectListItem> ();
			var service = new FormService ();
			var g = service.GetAll ().GetEnumerator ();
			while (g.MoveNext ()) {
				var sli = new SelectListItem ();
				sli.Text = g.Current.Name;
				sli.Value = g.Current.MyId.ToString ();
				//if (select != null && select.Id == g.Current.Id)
				//    sli.Selected = true;
				grades.Add (sli);
			}
			return grades;
		}

		public static IEnumerable<SelectListItem> getAllThinkTypeName ()
		{
			var grades = new List<SelectListItem> ();
			//var service = new ContentService();
			var g = SystemConst.ThinkTypeName.GetEnumerator ();
			while (g.MoveNext ()) {
				var sli = new SelectListItem ();
				sli.Text = g.Current.Value;
				sli.Value = ((int)g.Current.Key).ToString ();
				grades.Add (sli);
			}
			return grades;
		}

		public JsonResult RemoveActive (int acitveId)
		{
			return Json (true);
		}

		public ViewResult Detail (int id)
		{
			var service = new PlanService ();
			var plan = service.GetById (id);

			var model = new PlanDetail (plan);
			return View ("_Detail", model);
		}

		public PartialViewResult AddPlan ()
		{
			return PartialView ("_AddPlan");
		}

		[HttpPost]
		public JsonResult AddPlan (Plan model)
		{
			var service = new PlanService ();
			model.CreateDate = DateTime.Now;
			model.UserInfo_Id = int.Parse (Session ["user"].ToString ());
			//model.UserInfo = db.UserInfoSet.First(m => m.Id == uid);
			//model.Grade = db.GradeSet.First(m => m.Id == model.Grade.Id);
			//model.Subject = db.SubjectSet.First(m => m.Id == model.Subject.Id);
			//model.Textbook = db.TextbookSet.First(m => m.Id == model.Textbook.Id);
			service.Create (model);
			return Json (true);
		}

		public PartialViewResult LastCommentPlans ()
		{
			var cids = (new CommentService ()).GetLastCreate (ToType.Plan, 10);
			var pids = from p in cids
			           select p.To_Id;
			var enumer = (new PlanService ()).GetByIds (pids);
			return PartialView ("_PlanList", enumer);
		}

		public PartialViewResult LastViewPlans ()
		{
			var cids = (new ViewlogService ()).GetLastCreate (ToType.Plan, 10);
			var pids = from p in cids
			           select p.To_Id;
			var enumer = (new PlanService ()).GetByIds (pids);
			return PartialView ("_PlanList", enumer);
		}

		public PartialViewResult LastAddPlans ()
		{
			var service = new PlanService ();
			var enumer = service.GetLastCreate (10);
			return PartialView ("_PlanList", enumer);
		}

		[HttpGet]
		public PartialViewResult AddPoint (int planId)
		{
			var model = new Point ();
			model.planId = planId;
			return PartialView ("_AddPoint", model);
		}

		[HttpPost]
		[ValidateInput(false)]
		public JsonResult AddPoint (Point model)
		{
			var service = new PlanService ();
			var plan = service.GetById (model.planId);
			if (plan.Points == null)
				plan.Points = new List<Point> ();
			plan.Points.Add (model);
			service.UpdatePlan (model.planId, plan.Points);
			return Json (true);
		}

		[HttpGet]
		public PartialViewResult AddTarget (int planId)
		{
			var model = new Target ();
			model.planId = planId;
			return PartialView ("_AddTarget", model);
		}

		[HttpPost]
		[ValidateInput(false)]
		public JsonResult AddTarget (Target model)
		{
			var service = new PlanService ();
			var plan = service.GetById (model.planId);
			if (plan.Targets == null)
				plan.Targets = new List<Target> ();
			plan.Targets.Add (model);
			service.UpdatePlan (model.planId, plan.Targets);
			return Json (true);
		}

		[HttpGet]
		[ValidateInput(false)]
		public PartialViewResult AddThink (int planId)
		{
			var model = new Think ();
			model.planId = planId;
			return PartialView ("_AddThink", model);
		}

		[HttpPost]
		[ValidateInput(false)]
		public JsonResult AddTarget (Think model)
		{
			var service = new PlanService ();
			var plan = service.GetById (model.planId);
			if (plan.Thinks == null)
				plan.Thinks = new List<Think> ();
			plan.Thinks.Add (model);
			service.UpdatePlan (model.planId, plan.Thinks);
			return Json (true);
		}

		[HttpGet]
		public PartialViewResult UploadFile (int planId)
		{
			var model = new UploadFile ();
			model.planId = planId;
			return PartialView ("_UploadFile");
		}

		[HttpPost]
		public JsonResult UploadFile (UploadFile model)
		{
			if (Request.Files.Count > 0) {
				var file = Request.Files [0];
				if (file != null && file.ContentLength > 0) {
					var path = Server.MapPath ("~/plan_" + model.planId+ "/upload/");
					var fileExt = file.FileName.Substring (file.FileName.IndexOf ("."));
					var fileName = DateTime.Now.ToString ("yyMMddhhmmssfff");
					if (!Directory.Exists (path)) {
						Directory.CreateDirectory (path);
					}
					var savePath = Path.Combine (path, fileName) + fileExt;
					file.SaveAs (savePath);
					model.filePath = fileName + fileExt;
					var service = new PlanService ();
					var plan = service.GetById (model.planId);
					if (plan.Files == null)
						plan.Files = new List<UploadFile> ();
					plan.Files.Add (model);
					service.UpdatePlan (model.planId, plan.Files);
				}
			}
			return Json (true);
		}
	}
}

Views/Plan/Index.cshtml
@{
    ViewBag.Title = "优秀设计方案库";
}
<h2>
    优秀设计方案库</h2>
<input id="Button1" type="button" value="系统预置" />
<div>
    欢迎:</div>
<div>
    <input id="Button1" type="button" value="我参与的讨论" />
    <input id="Button1" type="button" value="我的方案" />
    <input id="Button1" type="button" value="系统预置" />
</div>
<div>
       @Ajax.ActionLink("添加新方案", "AddPlan", null, new AjaxOptions
  {
      OnSuccess = "OpenAddSctionDialog"
  }, new { @class = "action" })
</div>
<div>
    <fieldset>
            <legend>检索</legend>
       
    @Html.Partial("_Search")
</fieldset>
</div>
<div>

    <fieldset>
            <legend>最近添加</legend>
        
    @Html.Action("LastAddPlans")
</fieldset>
</div>
<div>
    <fieldset>
            <legend>最近浏览</legend>
        
    @Html.Action("LastViewPlans")
</fieldset>
</div>
<div>
    <fieldset>
            <legend>最新讨论</legend>
       
    @Html.Action("LastCommentPlans")
</fieldset>
</div>
<script type="text/javascript">
    var dialog;
    $(function () {
        dialog = $('#saveDialog').dialog({
            autoOpen: false,
            width: 640,
            height:480,
            resizable: false,
            modal: true
        });
    });
    function onAddPlanSucess(date) {
        alert("onAddPlanSucess");
    }
</script>

<div id="saveDialog" title="添加新方案">
</div>

Views/Plan/_Active.cshtml
@model TPlan.ActiveDetailModel

@Html.HiddenFor(m => m.MyId)
<div class="editor-label">
    @Model.Name @Ajax.ActionLink("删除引用该活动", "RemoveActive", new { acitveId = Model.MyId}, new AjaxOptions { OnSuccess = "onRemoveActive" }, new { @class = "action", @activeId = Model.MyId })
</div>
<div class="editor-label">
    学科:@Model.Subject.Name
</div>
<div class="editor-label">
    阶段:@Model.Phase.Name
</div>
<div class="editor-label">
    内容:@Model.Content.Name
</div>
<div class="editor-label">
    阶段:@Model.Form.Name
</div>

Views/Plan/_AddPlan.cshtml
@model TeachPlan.Plan
<div>
    @using (Ajax.BeginForm("AddPlan", "Plan", null, new AjaxOptions
        {
            // LoadingElementId="loading",
            // LoadingElementDuration=1,
            // UpdateTargetId="tabs-1",
            // InsertionMode = InsertionMode.InsertAfter,
            HttpMethod = "POST",
            OnSuccess = "onAddPlanSucess"
        }, new { @id = "addPlanForm" }))
    {
        <div class="editor-label">
            标题
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(m => m.Name)
            @Html.ValidationMessageFor(m => m.Name)
        </div>
        <div class="editor-label">
            作者
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Author)
            @Html.ValidationMessageFor(model => model.Author)
        </div>
        <div class="editor-label">
            简介
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Desc)
            @Html.ValidationMessageFor(model => model.Desc)
        </div>
        <div class="editor-label">
            课时名称
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(m => m.ClassName)
            @Html.ValidationMessageFor(m => m.ClassName)
        </div>
        <div class="editor-label">
            单位
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(m => m.Organiser)
            @Html.ValidationMessageFor(m => m.Organiser)
        </div>
        <div class="editor-label">
            公开
        </div>
        <div class="editor-field">
            @Html.CheckBoxFor(m => m.Public)
            @Html.ValidationMessageFor(m => m.Public)
        </div>
        <div class="editor-label">
            学科
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(m => m.Subject_Id, TeachPlan.Controllers.PlanController.getAllSubjects())
        </div>
        <div class="editor-label">
            年级
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(m => m.Grade_Id, TeachPlan.Controllers.PlanController.getAllGrades())
        </div>
        <div class="editor-label">
            教材
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(m => m.Textbook_Id, TeachPlan.Controllers.PlanController.getAllTextbooks())
        </div>         
                  <input id="Submit1" type="submit" value="提交" />                           
    }
</div>

Views/Plan/_AddPoint.cshtml
@model TeachPlan.Point

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>添加知识点</legend>
            @Html.HiddenFor(model => model.planId)
        <div class="editor-label">
            类型
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Type, TeachPlan.Controllers.ActiveController.getAllPoint())
            @Html.ValidationMessageFor(model => model.Type)
        </div>

        <div class="editor-label">
            内容
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Content)
            @Html.ValidationMessageFor(model => model.Content)
        </div>
        <div class="editor-label">
            方法
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Method)
            @Html.ValidationMessageFor(model => model.Method)
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

Views/Plan/_Detail.cshtml
@model Models.PlanDetail
@{
    ViewBag.Title = "教学方案";
}
<h2>@Model.Name - @Model.Author</h2>
<p>

</p>
<script>
    var dialog;
    $(function () {
        $("#tabs").tabs();

        dialog = $('#saveDialog').dialog({
            autoOpen: false,
            width: 450,
            resizable: false,
            modal: true
        });

    });
    function saveSucess(data) {
        alert(data);
    }
    function OnAddActiveSucess(data) {
        alert(data);
        dialog.dialog("close");
    }
    function OnAddStep(data) {
        dialog.html(data);
        dialog.dialog('open');
    }        
</script>
<div id="saveDialog" title="Address Information">
</div>
<div id="tabs">
    <ul>
        <li><a href="#tabs-1">基础信息</a></li>
        <li><a href="#tabs-2">教学目标</a></li>
        <li><a href="#tabs-3">学习者特征分析</a></li>
        <li><a href="#tabs-4">教学重点难点</a></li>
        <li><a href="#tabs-5">教学资源准备</a></li>
        <li><a href="#tabs-6">教学环节(活动)</a></li>
        <li><a href="#tabs-7">反思评价</a></li>
    </ul>
    <!--基础信息-->
    <div id="tabs-1">
        <p>
            @Html.Partial("_Plan", Model)
        </p>
    </div>
    <!--教学目标-->
    <div id="tabs-2">
        @Ajax.ActionLink("添加新目标", "AddTarget", "Plan", new { planId = Model.MyId }, new AjaxOptions
   {
       OnSuccess = "OpenAddSctionDialog"
   }, new { @class = "action" })
        <div>
            <div>
                <label>
                    知识技能
                </label>
                <ul>
                    @foreach (var item in Model.Targets.Where(m => (TeachPlan.TargetType)m.Type == TeachPlan.TargetType.ZhishiJineng))
                    {
                        @Html.Partial("_Target", item)
                    }
                </ul>
            </div>
            <div>
                <label>
                    过程方法
                </label>
                <ul>
                    @foreach (var item in Model.Targets.Where(m => (TeachPlan.TargetType)m.Type == TeachPlan.TargetType.GuochengFangfa))
                    {
                        @Html.Partial("_Target", item)
                    }
                </ul>
            </div>
            <div>
                <label>
                    情感态度
                </label>
                <ul>
                    @foreach (var item in Model.Targets.Where(m => (TeachPlan.TargetType)m.Type == TeachPlan.TargetType.QingganTaidu))
                    {
                        @Html.Partial("_Target", item)
                    }
                </ul>
            </div>
        </div>
    </div>
    <!--学习者特征分析-->
    <div id="tabs-3">
        <p>
           学习者特征分析
        </p>
    </div>
    <!--教学重点难点-->
    <div id="tabs-4">
        @Ajax.ActionLink("添加知识点", "AddPoint", "Plan", new { planId = Model.MyId }, new AjaxOptions
   {
       OnSuccess = "OpenAddSctionDialog"
   }, new { @class = "action" })
        <div>
            <label>
                重点
            </label>
            <ul>
                @foreach (var item in Model.Points.Where(m => (TeachPlan.PointType)m.Type == TeachPlan.PointType.Zhongdian))
                {
                    @Html.Partial("_Point", item)
                }
            </ul>
        </div>
        <div>
            <label>
                难点
            </label>
            <ul>
                @foreach (var item in Model.Points.Where(m => (TeachPlan.PointType)m.Type == TeachPlan.PointType.Nandian))
                {
                    @Html.Partial("_Point", item)
                }
            </ul>
        </div>
    </div>
    <!--教学资源准备-->
    <div id="tabs-5">
    @Ajax.ActionLink("添加新资源", "UploadFile", "Plan", new { planId = Model.MyId }, new AjaxOptions
   {
       OnSuccess = "OpenAddSctionDialog"
   }, new { @class = "action" })
        <div>
            <ul>
                @foreach (var item in Model.Files)
                {
                    <li>
                        <a href="/plan_@Model.MyId/upload/@item.filePath">@item.fileName</a>
                        @Html.Label(item.fileDesc)
                    </li>
                }
            </ul>
        </div>
    </div>
    <!--教学环节(活动)-->
    <div id="tabs-6">
        @Ajax.ActionLink("添加新活动", "AddActive", "Active", new { planId = Model.MyId }, new AjaxOptions
   {
       OnSuccess = "OpenAddSctionDialog"
   }, new { @class = "action" })
   @Ajax.ActionLink("引用现有活动", "SearchActives", "Active", new { userId = 0, formId=0,subjectId=Model.Subject.MyId,phaseId=0,contentId=0}, new AjaxOptions
   {
       OnSuccess = "OpenAddSctionDialog"
   }, new { @class = "action" })
        <div>
            <ul>
                @foreach (var item in Model.Actives)
                {
                    <li>
                        @Html.Partial("_Active", new TPlan.ActiveDetailModel(item))
                    </li>
                }
            </ul>
        </div>
    </div>
    <!--反思评价-->
    <div id="tabs-7">
     @Ajax.ActionLink("添加反思评价", "AddThink", "Plan", new { planId = Model.MyId }, new AjaxOptions
   {
       OnSuccess = "OpenAddSctionDialog"
   }, new { @class = "action" })
        <div>
            <label>
                反思
            </label><ul>
                @foreach (var item in Model.Thinks.Where(m=>m.Type==(int)TeachPlan.ThinkType.Fansi))
                {
                    @Html.Label(item.Content)
                }
            </ul>
        </div>
        <div>
            <label>
                评价
            </label><ul>
                @foreach (var item in Model.Thinks.Where(m=>m.Type==(int)TeachPlan.ThinkType.Pingjia))
                {
                    @Html.Label(item.Content)
                }
            </ul>
        </div>
    </div>
</div>

Views/Plan/_Method.cshtml
@model TeachPlan.Method
<li>
        @Html.TextAreaFor(m => m.Content)
</li>

Views/Plan/_Plan.cshtml
@model Models.PlanDetail
<div class="editor-field">
    标题:@Model.Name
</div>
<div class="editor-field">
    课时名称:@Model.ClassName
</div>
<div class="editor-field">
    单位:@Model.Organiser
</div>
<div class="editor-field">
    公开:@Model.Public
</div>
<div class="editor-field">
    学科:@Model.Subject.Name
</div>
<div class="editor-field">
    年级:@Model.Grade.Name
</div>
<div class="editor-field">
    教材:@Model.Textbook.Name
</div>

Views/Plan/_PlanList.cshtml
@model IEnumerable<TeachPlan.Plan>
<ul>
    @foreach (var item in Model)
    {
        
        <li>@Html.ActionLink(item.Name, "Detail", new {id=item.MyId})
        </li>
    }
</ul>

Views/Plan/_UploadFile.cshtml
@model TeachPlan.UploadFile

@using (Html.BeginForm("UploadFile", "Plan", FormMethod.Post, new { enctype = "multipart/form-data" })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>添加资源</legend>
            @Html.HiddenFor(model => model.planId)
        <div class="editor-label">
            类型
        </div>
       
        <div class="editor-label">
            名称
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.fileName)
            @Html.ValidationMessageFor(model => model.fileName)
        </div>
        <div class="editor-label">
            描述
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.fileDesc)
            @Html.ValidationMessageFor(model => model.fileDesc)
        </div>
<div class="editor-label">
            选择文件
        </div>
        <div class="editor-field">
<input type="file" name="FileUpload" />
        </div>
    <input type="submit" name="Submit" id="Submit" value="Upload" />
       
    </fieldset>
}