Controllers/KnowledgeController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Models;

namespace TeachPlan.Controllers
{
    public class KnowledgeController : Controller
    {

        public ActionResult Index()
        {
            var catgorys = GetByParent(null);
            return View(catgorys);
        }

        public ActionResult Category()
        {
            return View();
        }

        public PartialViewResult LastCommentKnowledge()
        {
            var service = new KnowledgeService();
            var enumer = service.GetByIds(new int[] { 1, 2 });
            return PartialView("_KnowledgeList", enumer);
        }

        public PartialViewResult LastViewKnowledge()
        {
            var service = new KnowledgeService();
            var enumer = service.GetByIds(new int[] { 1, 2 });
            return PartialView("_KnowledgeList", enumer);
        }

        public PartialViewResult LastAddKnowledge()
        {
            var service = new KnowledgeService();
            var enumer = service.GetLastCreate(10);
            return PartialView("_KnowledgeList", enumer);
        }

		public PartialViewResult KnowledgeComments(int knowledgeId)
		{
			return PartialView ("_Comments", GetCommentByKnowledge(knowledgeId));
		}

		public Comment[] GetCommentByKnowledge(int knowledgeId)
        {
            var service = new CommentService();
			var enumer = service.GetKnowledgeComments(knowledgeId);
            return enumer.ToArray();
        }

        [HttpPost]
		public JsonResult AddComment(Comment comment)
        {
            var service = new CommentService();
            service.Create(comment);
            return Json(true);
        }

		[HttpGet]
		public PartialViewResult AddComment(int knowledgeId)
		{
			var comment = new Comment();
			comment.To_Type = (int)ToType.Knowledge;
			comment.To_Id = knowledgeId;
			return PartialView ("_AddComment", comment);
		}
			
		[HttpGet]
		public PartialViewResult AddKnowledge()
		{
			return PartialView ("_AddKnowledge",new Knowledge());
		}
			
		[HttpPost]
		[ValidateInput(false)]
		public JsonResult AddKnowledge(Knowledge knowledge)
		{
			var service = new KnowledgeService ();
			//FormCollection collection = new FormCollection(Request.Unvalidated().Form);

			service.Create (knowledge);
			return Json (true);
		}

		public ViewResult KnowledgeDetail(int id)
		{
			var service = new KnowledgeService ();
			var knowlege = service.GetById (id);
			return View ("_KnowledgeDetail", knowlege);
		}

        public KnowledgeCategory AddCategory(KnowledgeCategory parent)
        {
            var category = new KnowledgeCategory();
            category.ParentCategory_Id = parent.MyId;
            var service = new KnowledgeCategoryService();
            service.Create(category);
            return category;
        }

        public KnowledgeCategory[] GetByParent(KnowledgeCategory parent)
        {
            var service = new KnowledgeCategoryService();
            IEnumerable<KnowledgeCategory> enumer;
            if (parent == null)
                enumer = service.GetChildCategory(0);
            else
                enumer = service.GetChildCategory(parent.MyId);
            return enumer.ToArray();
        }

        public Knowledge[] GetKnowledgeByCategory(KnowledgeCategory category)
        {
            var enumer = (new KnowledgeService()).GetKnowledgesByCategoryId(category.MyId);
            return enumer.ToArray();
        }

        public PartialViewResult CategoryTree()
        {
            var service = new KnowledgeCategoryService();
            List<KnowledgeCategoryTreeModel> model = new List<KnowledgeCategoryTreeModel>();
            var tops = service.GetChildCategory(0);
            foreach (var top in tops)
            {
                var t = new KnowledgeCategoryTreeModel(top);
                t.ChildCategorys = service.GetChildCategory(t.MyId);
                model.Add(t);
            }
            return PartialView("_CategoryTree", model);
        }
    }
}

Views/Knowledge/Index.cshtml
@{
    ViewBag.Title = "知识库";
}
    <h2>知识库</h2>

<script type="text/javascript">
	

</script>
    <script type="text/javascript">
		$(document).ready(function() {
			dialog = $('#saveDialog').dialog({
	            autoOpen: false,
	            width: 450,
	            resizable: false,
	            modal: true
	        });
		});
		function onAddKnowledge(data){

		}

	</script>
	@Ajax.ActionLink("添加新知识", "AddKnowledge", "Knowledge", null, new AjaxOptions
   {
       OnSuccess = "OpenAddSctionDialog"
   }, new { @class = "action" })
<div>
   <fieldset>
            <legend>分类</legend>
@Html.Action("CategoryTree")
            </fieldset>
            </div>
            <div><fieldset><legend>最近评论</legend>

@Html.Action("LastCommentKnowledge")
            </fieldset></div>
<div><fieldset><legend>最近查看</legend>
@Html.Action("LastViewKnowledge")
           </fieldset></div>
   <div>
        <fieldset>
            <legend>最后添加</legend>
@Html.Action("LastAddKnowledge")
            </fieldset>
            </div>

<div id="saveDialog" title="Address Information">
</div>

Views/Knowledge/_AddComment.cshtml
@model TeachPlan.KnowledgeComment


@using (Ajax.BeginForm("AddComment", "Knowledge", new AjaxOptions
{
    OnSuccess = "onAddCommentSucess",
    UpdateTargetId = "comments",
    InsertionMode = InsertionMode.InsertAfter
}, new { @id = "addCommentForm" }))
{
    <div class="editor-label">
        @Html.LabelFor(m => m.Content)
    </div>
    <div class="editor-field">
        @Html.TextBoxFor(m => m.Content)
        @Html.ValidationMessageFor(m => m.Content)
    </div>
}

Views/Knowledge/_AddKnowledge.cshtml
@model TeachPlan.Knowledge


@using (Ajax.BeginForm("AddKnowledge", "Knowledge", new AjaxOptions
{
    OnSuccess = "onAddKnowledge",
    UpdateTargetId = "comments",
    InsertionMode = InsertionMode.InsertAfter
}, new { @id = "addKnowledgeForm" }))
{
    <div class="editor-label">
        @Html.LabelFor(m => m.Title)
    </div>
    <div class="editor-field">
        @Html.TextBoxFor(m => m.Title)
        @Html.ValidationMessageFor(m => m.Title)
    </div>
    <div class="editor-label">
        @Html.LabelFor(m => m.Content)
    </div>
    <div class="editor-field">
        @Html.TextAreaFor(m => m.Content,new {id="knowledge_content"})
        @Html.ValidationMessageFor(m => m.Content)
    </div>

     <input id="submit" type="submit" value="提交" />
}

Views/Knowledge/_CategoryTree.cshtml
<script src="@Url.Content("~/Scripts/jquery.treeview.js")" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#navigation").treeview({
            persist: "location",
            collapsed: true,
            unique: true
        });
    });
</script>

@model IEnumerable<Models.KnowledgeCategoryTreeModel>
<ul id="navigation">
    @foreach (var parent in Model)
    {
        <li><a href="?@parent.Id">@parent.CategoryName</a>
            @if (parent.ChildCategorys.Count() > 0)
            {
                <ul>
                    @foreach (var child in parent.ChildCategorys)
                    {
                        <li class="open"><a href="?@child.Id">@child.CategoryName</a> </li>
                    }
                </ul>
            }
        </li>
    }
</ul>

Views/Knowledge/_KnowledgeDetail.cshtml
@model TeachPlan.Knowledge
<div>@Model.Title</div>
<div>@Model.CreateDate.ToString("YYYY-MM-DD hh:mm")</div>
<div>@Html.Raw(Model.Content)</div>

@Html.Action("KnowledgeComments","Knowledge",new {knowledgeId=Model.MyId})
@Html.Action("AddComment","Knowledge",new {knowledgeId=Model.MyId})

Views/Knowledge/_KnowledgeList.cshtml
@model IEnumerable<TeachPlan.Knowledge>
<div>
    @foreach (var item in Model)
    {
        <li>
            <label>
            @Html.ActionLink(item.Title,"KnowledgeDetail",new {id=item.MyId})
            </label>
            <label>
                @String.Format("{0:g}", item.CreateDate)
            </label>
        </li>
    }
</div>